### ISSUE TITLE
Return back the author name

### ISSUE THREAD

**Issue by KostyaEsmukov** [scott-8/smtp-gotify#1]
This is a derivative of my work and I noticed that my name has been removed from the list of authors in the license, effectively wiping the statutory attribution: https://github.com/scott-8/smtp-gotify/commit/f464ad5319aea88d3fe8849a33681baf1f6e2c2e#diff-9879d6db96fd29134fc802214163b95aL3

Could you please return back the copyright line? Thanks in advance!

See also https://softwareengineering.stackexchange.com/a/386584

**Comment by scott-8** [comment]
Sure thing, my mistake.
